Milestone 5: Full website
willy836/Math-Magicians pull request #6
Opened 2023-01-17 11:35 UTC by willy836

**Math magicians Milestone 4: Full website**
In this milestone, I:

- created a full website for the Math magicians app, consisting of 3 pages: home, calculator, and quote

2023-01-17 12:06 UTC, gemmen29 requested changes
Hi @willy836, 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

## Highlights 💯 
- No linters errors ✔️ 
- Descriptive pull request ✔️ 
- Descriptive commit messages ✔️ 

## Required Changes ♻️
_Check the comments under the review._

![](https://media.giphy.com/media/tKyrc0NTlEcGWdThp4/giphy.gif)

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-01-17 12:06 UTC, gemmen29 commented on src/index.css
> +nav {
- [ ] Kindly use what you already learn in [React basic styling](https://github.com/microverseinc/curriculum-react-redux/blob/main/math-magicians/articles/react_basic_styling.md) lesson for styling your app as per this [requirement](https://github.com/microverseinc/curriculum-react-redux/blob/main/math-magicians/project_full_website.md#:~:text=In%20this%20project%2C%20you%20should%20use%20React%20basic%20styling.) instead of adding general style in the `index.css` file.

2023-01-17 12:06 UTC, gemmen29 commented on src/index.css
> +  font-family: "Poppins", sans-serif;
- [ ] [OPTIONAL] Good job on following the design guidelines wireframe for styling your app. I encourage you to add more styles in order to improve the look and feel and to make it your own.

2023-01-17 12:44 UTC, willy836 commented on src/index.css
> +nav {
hi @gemmen29 
Thanks for the review and feedback. I however think that I followed React basic styling - I used inline styles, and imported CSS (which you can write in one or several CSS files). What I did not do was use SASS, which I dont think was mandatory to use.

2023-01-17 14:18 UTC, 1GORDON approved these changes
# Status: APPROVED 🟢 

Hi @willy836 ✋

Your project is complete!  There is nothing else to say other than... it's time to merge it: ship it:
Congratulations! :tada: :clap: :clap: :100:

## Highlights!
- Followed Gitflow ✔️
- Linters are passing ✔️
- Professional readme ✔️

## Optional suggestions

- [ ] You may remove the live demo link from your readme file since the project is not deployed.

_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you consider them as they can improve your code._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread and tag me `@1GORDON` if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think the code review was unfair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-01-17 14:34 UTC, merged

2023-01-18 09:50 UTC, gemmen29 commented on src/index.css
> +nav {
Hi @willy836 sorry for the late response I see that your PR has already been approved. In your PR you put all the styles in the `index.css` file in the lesson of [React Basic style](https://github.com/microverseinc/curriculum-react-redux/blob/main/math-magicians/articles/react_basic_styling.md) they encourage you to use either the inline styles like [this](https://github.com/microverseinc/curriculum-react-redux/blob/main/math-magicians/articles/react_basic_styling.md#:~:text=Inline%20styles,myStyle%7D%3E%3C/div%3E) or using different CSS files one for each component like [this](https://github.com/microverseinc/curriculum-react-redux/blob/main/math-magicians/articles/react_basic_styling.md#:~:text=Importing%20CSS,up%20for%20you.). You don't need to use pre-processed like sass.